This commit was manufactured by cvs2git to create tag 'STABLE'.
Sprout from master 2003-08-05 14:03:17 UTC Jakub Bogusz <qboosh@pld-linux.org> '- two more wrong type, few other bugs'
Cherrypick from master 2001-06-24 22:45:30 UTC Jakub Bogusz <qboosh@pld-linux.org> '- fixed setgroups patch (builds now)':
    LPRng-direct.patch -> 1.1
    LPRng-inet_ntop.patch -> 1.1
    LPRng-lockfile.patch -> 1.1
    LPRng-setgroups.patch -> 1.2
Cherrypick from master 2002-07-10 01:07:40 UTC kloczek <kloczek@pld-linux.org> '- updated for 3.8.12.':
    LPRng-nproc-unlimited.patch -> 1.1
    LPRng-shutdown.patch -> 1.3
    LPRng.init -> 1.4
Cherrypick from master 2000-07-21 15:07:32 UTC kloczek <kloczek@pld-linux.org> '- patch checkpc to not complain when filter is executable and in the':
    LPRng-autoconf.patch -> 1.5
    LPRng-filter.patch -> 1.1
Cherrypick from master 1999-08-05 20:53:33 UTC kloczek <kloczek@pld-linux.org> '- fix in checking is netforking is up.':
    lpd.init -> 1.5

diff --git a/lpd.init b/lpd.init
--- a/lpd.init
+++ b/lpd.init
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# lpd		This shell script takes care of starting and stopping
-#		lpd (printer daemon).
+# lpd           This shell script takes care of starting and stopping
+#               lpd (printer daemon).
 #
 # chkconfig:	2345 60 60
 #
@@ -22,54 +22,42 @@
 [ -f /etc/sysconfig/lpd ] && . /etc/sysconfig/lpd
 
 # Check that networking is up.
-if is_yes "${NETWORKING}"; then
-	if [ ! -f /var/lock/subsys/network -a "$1" != stop -a "$1" != status ]; then
-		msg_network_down Lpd
-		exit 1
-	fi
-else
-	exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Lpd can't be runed."
+	exit 1
 fi
-			
-# Sanity check
-[ -f /etc/printcap ] || exit 1
 
-RETVAL=0
+# Sanity check
+[ -f /etc/printcap ] || exit 0
+
+
 # See how we were called.
 case "$1" in
   start)
 	# Check if the service is already running?
 	if [ ! -f /var/lock/subsys/lpd ]; then
-		msg_starting Lpd
+		show Starting lpd
 		daemon lpd
-		RETVAL=$?
-		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/lpd
 	else
-		msg_already_running Lpd
+		echo "lpd already is running"
 	fi
-	;;
+        touch /var/lock/subsys/lpd
+        ;;
   stop)
-	# Stop daemons.
-	if [ -f /var/lock/subsys/lpd ]; then
-		msg_stopping Lpd
-		killproc lpd
-		rm -f /var/lock/subsys/lpd >/dev/null 2>&1
-	else
-		msg_not_running Lpd
-	fi
-	;;
+        show "Shutting down lpd"
+	killproc lpd
+        rm -f /var/lock/subsys/lpd
+        ;;
   status)
 	status lpd
-	exit $?
 	;;
-  restart|force-reload)
+  restart|reload)
 	$0 stop
 	$0 start
-	exit $?
 	;;
   *)
-	msg_usage "$0 {start|stop|restart|force-reload|status}"
-	exit 3
+        echo "Usage: $0 {start|stop|status|restart|reload}"
+        exit 1
 esac
 
-exit $RETVAL
+exit 0
