updated to 3.7.5
Changed files:
    LPRng-ac_fixes.patch -> 1.7

diff --git a/LPRng-ac_fixes.patch b/LPRng-ac_fixes.patch
--- a/LPRng-ac_fixes.patch
+++ b/LPRng-ac_fixes.patch
@@ -1,6 +1,193 @@
-diff -Nru LPRng-3.7.2/configure.in LPRng-3.7.2.new/configure.in
---- LPRng-3.7.2/configure.in	Thu Dec 21 20:42:25 2000
-+++ LPRng-3.7.2.new/configure.in	Thu Dec 21 20:45:20 2000
+--- LPRng-3.7.5/src/Makefile.in.wiget	Wed Jan 10 01:59:06 2001
++++ LPRng-3.7.5/src/Makefile.in	Tue Oct  9 14:53:05 2001
+@@ -33,7 +33,8 @@
+ @SET_MAKE@
+ 
+ # what C compiler to use.
+-CC:=@CC@
++CC=@CC@
++datadir=@datadir@
+ 
+ # what command to use to "ranlib" or "lorder" the library.
+ RANLIB=@RANLIB@
+@@ -47,14 +48,9 @@
+ SHELL_PATH=@SHELL@
+ SHELL = @SHELL@
+ 
+-# loader for c programs
+-LDCC=@LDCC@
+-
+ # any libs that need to be used to get these programs to compile:
+-LIBS=@USE_GDBM_LIB@ @INTLLIBS@ @LIBS@
++LIBS=@LIBS@
+ 
+-# add path to internationalization
+-INTLINCS=@INTLINCS@
+ 
+ ### PATHS ####
+ # prefix
+@@ -72,12 +68,10 @@
+ 
+ # install options
+ 
+-STRIP=@STRIP@
+ 
+ CFLAGS:= @CPPFLAGS@ @CFLAGS@ @DEFS@ \
+  -I${top_builddir} \
+- -I${SRC}/include -I${SRC}/common @INTLINCS@ \
+- -I@USE_GDBM_INC_DIR@ \
++ -I${SRC}/include -I${SRC}/common \
+  -DCHOWN=\"@CHOWN@\"  \
+  -DCHGRP=\"@CHGRP@\"  \
+  -DPRINTCAP_PATH=\"@PRINTCAP_PATH@\"  \
+@@ -91,16 +85,15 @@
+  -DCLEAR=\"@CLEAR@\"  \
+  -DUSERID=\"@USERID@\"  \
+  -DGROUPID=\"@GROUPID@\"  \
+- -DLOCALEDIR=\"@LOCALEDIR@\"
++ -DLOCALEDIR=\"$(datadir)/locale\"
+ 
+ 
+ USER_OBJS := @USER_OBJS@
+-LDFLAGS   := -L@USE_GDBM_LIB_DIR@ @LDFLAGS@
++LDFLAGS   := @LDFLAGS@
+ 
+ FILTER_DIR = @FILTER_DIR@
+ LPD_DIR    = @LPD_DIR@
+ 
+-STRIP      = @STRIP@
+ 
+ #********************** End of configure modifiable settings ************
+ 
+@@ -178,7 +171,7 @@
+ 
+ 
+ SRCDIRS=${SRC}/common ${SRC}/AUTHENTICATE
+-INCLUDE=.. ${SRC}/include ${INTLINCS}
++INCLUDE=.. ${SRC}/include
+ 
+ VPATH=..:.:${SRC}/include:${SRC}/common
+ 
+@@ -244,33 +237,33 @@
+ 	$(RANLIB) $@
+ 
+ lpd: $(LPD_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPD_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPD_OBJS} liblpr.a $(LIBS)
+ lpr: $(LPR_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPR_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPR_OBJS} liblpr.a $(LIBS)
+ lpq: $(LPQ_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPQ_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPQ_OBJS} liblpr.a $(LIBS)
+ lpstat: $(LPSTAT_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPSTAT_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPSTAT_OBJS} liblpr.a $(LIBS)
+ lprm: $(LPRM_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPRM_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPRM_OBJS} liblpr.a $(LIBS)
+ lpc: $(LPC_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPC_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPC_OBJS} liblpr.a $(LIBS)
+ checkpc: $(CHECKPC_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${CHECKPC_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${CHECKPC_OBJS} liblpr.a $(LIBS)
+ lpf: $(LPF_OBJS)
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPF_OBJS} $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPF_OBJS} $(LIBS)
+ lpbanner: $(LPBANNER_OBJS)
+-	$(LDCC) $(LDFLAGS) -o $@ ${LPBANNER_OBJS} $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${LPBANNER_OBJS} $(LIBS)
+ monitor: $(MONITOR_OBJS) liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ ${MONITOR_OBJS} liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ ${MONITOR_OBJS} liblpr.a $(LIBS)
+ 
+ authenticate_pgp: ${SRC}/AUTHENTICATE/authenticate_pgp.sh
+ 	rm -f $@; cp ${SRC}/AUTHENTICATE/authenticate_pgp.sh $@; chmod 555 $@
+ 
+ sserver: sserver.o liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ sserver.o liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ sserver.o liblpr.a $(LIBS)
+ sclient: sclient.o liblpr.a
+-	$(LDCC) $(LDFLAGS) -o $@ sclient.o liblpr.a $(LIBS)
++	$(CC) $(LDFLAGS) -o $@ sclient.o liblpr.a $(LIBS)
+ 
+ sendauth.o lpd_secure.o :	user_auth.stub
+ 
+@@ -307,17 +300,17 @@
+ 	  if [ ! -d $$i ] ; then ${SRC}/mkinstalldirs $$i ; fi; \
+ 	done;
+ 
+-	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpq ${DESTDIR}${bindir}
+-	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lprm ${DESTDIR}${bindir}
+-	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpr ${DESTDIR}${bindir}
+-	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpstat ${DESTDIR}${bindir}
+-	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpc ${DESTDIR}${sbindir}
+-	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) lpd ${DESTDIR}${LPD_DIR}
+-	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) lpf ${DESTDIR}${FILTER_DIR}
+-	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) lpbanner ${DESTDIR}${FILTER_DIR}
+-	${INSTALLCMD}    -m $(NORM_PERMS) pclbanner ${DESTDIR}${FILTER_DIR}
+-	${INSTALLCMD}    -m $(NORM_PERMS) psbanner ${DESTDIR}${FILTER_DIR}
+-	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) checkpc ${DESTDIR}${sbindir}
++	${INSTALLCMD} -m $(@PERMS@) lpq ${DESTDIR}${bindir}
++	${INSTALLCMD} -m $(@PERMS@) lprm ${DESTDIR}${bindir}
++	${INSTALLCMD} -m $(@PERMS@) lpr ${DESTDIR}${bindir}
++	${INSTALLCMD} -m $(@PERMS@) lpstat ${DESTDIR}${bindir}
++	${INSTALLCMD} -m $(@PERMS@) lpc ${DESTDIR}${sbindir}
++	${INSTALLCMD} -m $(NORM_PERMS) lpd ${DESTDIR}${LPD_DIR}
++	${INSTALLCMD} -m $(NORM_PERMS) lpf ${DESTDIR}${FILTER_DIR}
++	${INSTALLCMD} -m $(NORM_PERMS) lpbanner ${DESTDIR}${FILTER_DIR}
++	${INSTALLCMD} -m $(NORM_PERMS) pclbanner ${DESTDIR}${FILTER_DIR}
++	${INSTALLCMD} -m $(NORM_PERMS) psbanner ${DESTDIR}${FILTER_DIR}
++	${INSTALLCMD} -m $(NORM_PERMS) checkpc ${DESTDIR}${sbindir}
+ 	cd ${DESTDIR}${bindir}; rm -f lp cancel; ln -s lpr lp; ln -s lprm cancel;
+ 
+ uninstall:
+--- LPRng-3.7.5/man/Makefile.in.wiget	Mon Jan  8 20:19:50 2001
++++ LPRng-3.7.5/man/Makefile.in	Tue Oct  9 14:53:05 2001
+@@ -22,8 +22,8 @@
+ 
+ ## fix up prefix to be a make variable
+ prefix = @prefix@
+-MAN =		@mandir@
+-SHELL =		@SHELL@
++mandir = @mandir@
++SHELL =	@SHELL@
+ 
+ # Install man pages in compressed form.
+ # COMPRESS     = compression utility
+@@ -61,13 +61,13 @@
+ install:
+ 	for suffix in 1 2 3 4 5 6 7 8 ; do \
+ 	  if ls ${SRC}/*.$${suffix} >/dev/null 2>&1 ; then \
+-	    if [ ! -d $(DESTDIR)$(MAN)/man$${suffix} ] ; then \
+-		    echo ${SRC}/mkinstalldirs $(DESTDIR)$(MAN)/man$${suffix}; \
+-		    ${SRC}/mkinstalldirs $(DESTDIR)$(MAN)/man$${suffix}; \
++	    if [ ! -d $(DESTDIR)$(mandir)/man$${suffix} ] ; then \
++		    echo ${SRC}/mkinstalldirs $(DESTDIR)$(mandir)/man$${suffix}; \
++		    ${SRC}/mkinstalldirs $(DESTDIR)$(mandir)/man$${suffix}; \
+ 	    fi; \
+ 	    for i in ${SRC}/*.$$suffix; do \
+-		echo   $(INSTALL) -m 644 $$i $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
+-		$(INSTALL)   -m 644 $$i $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
++		echo   $(INSTALL) -m 644 $$i $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(mandirEXT); \
++		$(INSTALL)   -m 644 $$i $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(mandirEXT); \
+ 	    done; \
+ 	  fi; \
+ 	done;
+@@ -76,8 +76,8 @@
+ 	for suffix in 1 2 3 4 5 6 7 8 ; do \
+ 	  if ls ${SRC}/*.$${suffix} >/dev/null 2>&1 ; then \
+ 	    for i in ${SRC}/*.$$suffix; do \
+-		echo   rm $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
+-		rm   $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
++		echo   rm $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(mandirEXT); \
++		rm   $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(MANEXT); \
+ 	    done; \
+ 	  fi; \
+ 	done;
+--- LPRng-3.7.5/configure.in.wiget	Mon Jan 15 21:26:40 2001
++++ LPRng-3.7.5/configure.in	Tue Oct  9 14:53:05 2001
 @@ -13,46 +13,13 @@
  AC_CANONICAL_SYSTEM
  AC_CONFIG_HEADER(config.h)
@@ -52,7 +239,39 @@ diff -Nru LPRng-3.7.2/configure.in LPRng-3.7.2.new/configure.in
  
  dnl ----------------------------------------------------------------------------
  dnl ----------- XXXXXX START OF OPTIONS ----------------------------------------
-@@ -331,38 +298,11 @@
+@@ -86,31 +53,6 @@
+ 	USE_GDBM_BUILD_DIR=`pwd`/db
+ 	USE_GDBM_LIB_DIR=`pwd`/db/.libs
+ 	USE_GDBM_INC_DIR=`pwd`/db
+-	d=${srcdir}/${USE_GDBM}
+-#	USE_GDBM=db-3.1.17
+-#	USE_GDBM_LIB="-ldb"
+-#	USE_GDBM_BUILD_DIR=`pwd`/db
+-#	USE_GDBM_LIB_DIR=`pwd`/db
+-#	USE_GDBM_INC_DIR=`pwd`/db
+-#	d=${srcdir}/${USE_GDBM}/dist
+-	if test "!" -d db ; then
+-		mkdir db
+-	fi
+-	if test "!" -d ${d} ; then
+-		echo "Missing $d";
+-		exit 1
+-	fi
+-	e=`cd $d; pwd`
+-	echo DIR $d is $e
+-	f=$e/configure
+-	if test "!" -f $f ; then
+-		echo "Missing $f";
+-		exit 1
+-	fi
+-	echo "#!/bin/sh
+-/bin/sh $f \"\$@\" --srcdir=$e
+-" >db/configure
+-	chmod a+x db/configure
+ fi
+ AC_SUBST(USE_GDBM)dnl
+ AC_SUBST(USE_GDBM_LIB)dnl
+@@ -382,38 +324,11 @@
  AC_MSG_RESULT($FILTER_DIR)
  AC_SUBST(FILTER_DIR)
  
@@ -91,7 +310,7 @@ diff -Nru LPRng-3.7.2/configure.in LPRng-3.7.2.new/configure.in
  dnl ----------------------------------------------------------------------------
  dnl ------------   OS Checks  --------------------------------------------------
  AC_ISC_POSIX
-@@ -1322,38 +1262,9 @@
+@@ -1359,38 +1274,9 @@
  SHELL=/bin/sh
  AC_MSG_RESULT(using $SHELL (FORCED))
  
@@ -131,15 +350,19 @@ diff -Nru LPRng-3.7.2/configure.in LPRng-3.7.2.new/configure.in
  dnl ----------------------------------------------------------------------------
  dnl ----------------- END OF GENERAL CONFIGURATION   ---------------------------
  
-@@ -1489,7 +1400,6 @@
+@@ -1525,11 +1411,7 @@
+ fi;
  
  
+-if test "$USE_GDBM" != ""  ; then
+-	AC_CONFIG_SUBDIRS( db )
+-fi
  AC_OUTPUT(
 -[
  Makefile
  HOWTO/Makefile
  TESTSUPPORT/Makefile
-@@ -1519,28 +1429,22 @@
+@@ -1558,28 +1440,22 @@
  src/psbanner
  po/Makefile.in
  intl/Makefile
@@ -184,198 +407,8 @@ diff -Nru LPRng-3.7.2/configure.in LPRng-3.7.2.new/configure.in
  )
  
  dnl ----------------------------------------------------------------------------
-diff -Nru LPRng-3.7.2/man/Makefile.in LPRng-3.7.2.new/man/Makefile.in
---- LPRng-3.7.2/man/Makefile.in	Thu Dec 21 20:42:25 2000
-+++ LPRng-3.7.2.new/man/Makefile.in	Thu Dec 21 20:41:40 2000
-@@ -22,8 +22,8 @@
- 
- ## fix up prefix to be a make variable
- prefix = @prefix@
--MAN =		@mandir@
--SHELL =		@SHELL@
-+mandir = @mandir@
-+SHELL =	@SHELL@
- 
- # Install man pages in compressed form.
- # COMPRESS     = compression utility
-@@ -61,13 +61,13 @@
- install:
- 	for suffix in 1 2 3 4 5 6 7 8 ; do \
- 	  if ls ${SRC}/*.$${suffix} >/dev/null 2>&1 ; then \
--	    if [ ! -d $(DESTDIR)$(MAN)/man$${suffix} ] ; then \
--		    echo ${SRC}/mkinstalldirs $(DESTDIR)$(MAN)/man$${suffix}; \
--		    ${SRC}/mkinstalldirs $(DESTDIR)$(MAN)/man$${suffix}; \
-+	    if [ ! -d $(DESTDIR)$(mandir)/man$${suffix} ] ; then \
-+		    echo ${SRC}/mkinstalldirs $(DESTDIR)$(mandir)/man$${suffix}; \
-+		    ${SRC}/mkinstalldirs $(DESTDIR)$(mandir)/man$${suffix}; \
- 	    fi; \
- 	    for i in ${SRC}/*.$$suffix; do \
--		echo   $(INSTALL) -m 644 $$i $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
--		$(INSTALL)   -m 644 $$i $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
-+		echo   $(INSTALL) -m 644 $$i $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(mandirEXT); \
-+		$(INSTALL)   -m 644 $$i $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(mandirEXT); \
- 	    done; \
- 	  fi; \
- 	done;
-@@ -76,8 +76,8 @@
- 	for suffix in 1 2 3 4 5 6 7 8 ; do \
- 	  if ls ${SRC}/*.$${suffix} >/dev/null 2>&1 ; then \
- 	    for i in ${SRC}/*.$$suffix; do \
--		echo   rm $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
--		rm   $(DESTDIR)$(MAN)/man$$suffix/`basename $$i`$(MANEXT); \
-+		echo   rm $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(mandirEXT); \
-+		rm   $(DESTDIR)$(mandir)/man$$suffix/`basename $$i`$(MANEXT); \
- 	    done; \
- 	  fi; \
- 	done;
-diff -Nru LPRng-3.7.2/src/Makefile.in LPRng-3.7.2.new/src/Makefile.in
---- LPRng-3.7.2/src/Makefile.in	Thu Dec 21 20:42:25 2000
-+++ LPRng-3.7.2.new/src/Makefile.in	Thu Dec 21 20:41:40 2000
-@@ -33,7 +33,8 @@
- @SET_MAKE@
- 
- # what C compiler to use.
--CC:=@CC@
-+CC=@CC@
-+datadir=@datadir@
- 
- # what command to use to "ranlib" or "lorder" the library.
- RANLIB=@RANLIB@
-@@ -47,15 +48,9 @@
- SHELL_PATH=@SHELL@
- SHELL = @SHELL@
- 
--# loader for c programs
--LDCC=@LDCC@
--
- # any libs that need to be used to get these programs to compile:
- LIBS=@INTLLIBS@ @LIBS@
- 
--# add path to internationalization
--INTLINCS=@INTLINCS@
--
- ### PATHS ####
- # prefix
- prefix=@prefix@
-@@ -72,10 +67,8 @@
- 
- # install options
- 
--STRIP=@STRIP@
--
- CFLAGS:= @CPPFLAGS@ @CFLAGS@ @DEFS@ \
-- -I.. -I${SRC}/include -I${SRC}/common @INTLINCS@ \
-+ -I.. -I${SRC}/include -I${SRC}/common \
-  -DCHOWN=\"@CHOWN@\"  \
-  -DCHGRP=\"@CHGRP@\"  \
-  -DPRINTCAP_PATH=\"@PRINTCAP_PATH@\"  \
-@@ -88,17 +81,14 @@
-  -DLOCKFILE=\"@LOCKFILE@\"  \
-  -DCLEAR=\"@CLEAR@\"  \
-  -DUSERID=\"@USERID@\"  \
-- -DGROUPID=\"@GROUPID@\"  \
-- -DLOCALEDIR=\"@LOCALEDIR@\"
--
-+ -DGROUPID=\"@GROUPID@\" \
-+ -DLOCALEDIR=\"$(datadir)/locale\"
- 
- USER_OBJS := @USER_OBJS@
- LDFLAGS   := @LDFLAGS@
- FILTER_DIR = @FILTER_DIR@
- LPD_DIR    = @LPD_DIR@
- 
--STRIP      = @STRIP@
--
- #********************** End of configure modifiable settings ************
- 
- 
-@@ -175,7 +165,7 @@
- 
- 
- SRCDIRS=${SRC}/common ${SRC}/AUTHENTICATE
--INCLUDE=.. ${SRC}/include ${INTLINCS}
-+INCLUDE=.. ${SRC}/include
- 
- VPATH=..:.:${SRC}/include:${SRC}/common
- 
-@@ -241,33 +231,33 @@
- 	$(RANLIB) $@
- 
- lpd: $(LPD_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${LPD_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPD_OBJS} liblpr.a $(LIBS)
- lpr: $(LPR_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${LPR_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPR_OBJS} liblpr.a $(LIBS)
- lpq: $(LPQ_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${LPQ_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPQ_OBJS} liblpr.a $(LIBS)
- lpstat: $(LPSTAT_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${LPSTAT_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPSTAT_OBJS} liblpr.a $(LIBS)
- lprm: $(LPRM_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${LPRM_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPRM_OBJS} liblpr.a $(LIBS)
- lpc: $(LPC_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${LPC_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPC_OBJS} liblpr.a $(LIBS)
- checkpc: $(CHECKPC_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${CHECKPC_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${CHECKPC_OBJS} liblpr.a $(LIBS)
- lpf: $(LPF_OBJS)
--	$(LDCC) $(LDFLAGS) -o $@ ${LPF_OBJS} $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPF_OBJS} $(LIBS)
- lpbanner: $(LPBANNER_OBJS)
--	$(LDCC) $(LDFLAGS) -o $@ ${LPBANNER_OBJS} $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${LPBANNER_OBJS} $(LIBS)
- monitor: $(MONITOR_OBJS) liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ ${MONITOR_OBJS} liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ ${MONITOR_OBJS} liblpr.a $(LIBS)
- 
- authenticate_pgp: ${SRC}/AUTHENTICATE/authenticate_pgp.sh
- 	rm -f $@; cp ${SRC}/AUTHENTICATE/authenticate_pgp.sh $@; chmod 555 $@
- 
- sserver: sserver.o liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ sserver.o liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ sserver.o liblpr.a $(LIBS)
- sclient: sclient.o liblpr.a
--	$(LDCC) $(LDFLAGS) -o $@ sclient.o liblpr.a $(LIBS)
-+	$(CC) $(LDFLAGS) -o $@ sclient.o liblpr.a $(LIBS)
- 
- sendauth.o lpd_secure.o :	user_auth.stub
- 
-@@ -304,17 +294,17 @@
- 	  if [ ! -d $$i ] ; then ${SRC}/mkinstalldirs $$i ; fi; \
- 	done;
- 
--	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpq ${DESTDIR}${bindir}
--	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lprm ${DESTDIR}${bindir}
--	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpr ${DESTDIR}${bindir}
--	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpstat ${DESTDIR}${bindir}
--	${INSTALLCMD} ${STRIP} -m $(@PERMS@) lpc ${DESTDIR}${sbindir}
--	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) lpd ${DESTDIR}${LPD_DIR}
--	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) lpf ${DESTDIR}${FILTER_DIR}
--	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) lpbanner ${DESTDIR}${FILTER_DIR}
--	${INSTALLCMD}    -m $(NORM_PERMS) pclbanner ${DESTDIR}${FILTER_DIR}
--	${INSTALLCMD}    -m $(NORM_PERMS) psbanner ${DESTDIR}${FILTER_DIR}
--	${INSTALLCMD} ${STRIP} -m $(NORM_PERMS) checkpc ${DESTDIR}${sbindir}
-+	${INSTALLCMD} -m $(@PERMS@) lpq ${DESTDIR}${bindir}
-+	${INSTALLCMD} -m $(@PERMS@) lprm ${DESTDIR}${bindir}
-+	${INSTALLCMD} -m $(@PERMS@) lpr ${DESTDIR}${bindir}
-+	${INSTALLCMD} -m $(@PERMS@) lpstat ${DESTDIR}${bindir}
-+	${INSTALLCMD} -m $(@PERMS@) lpc ${DESTDIR}${sbindir}
-+	${INSTALLCMD} -m $(NORM_PERMS) lpd ${DESTDIR}${LPD_DIR}
-+	${INSTALLCMD} -m $(NORM_PERMS) lpf ${DESTDIR}${FILTER_DIR}
-+	${INSTALLCMD} -m $(NORM_PERMS) lpbanner ${DESTDIR}${FILTER_DIR}
-+	${INSTALLCMD} -m $(NORM_PERMS) pclbanner ${DESTDIR}${FILTER_DIR}
-+	${INSTALLCMD} -m $(NORM_PERMS) psbanner ${DESTDIR}${FILTER_DIR}
-+	${INSTALLCMD} -m $(NORM_PERMS) checkpc ${DESTDIR}${sbindir}
- 	cd ${DESTDIR}${bindir}; rm -f lp cancel; ln -s lpr lp; ln -s lprm cancel;
- 
- uninstall:
-diff -Nru LPRng-3.7.4/Makefile.in LPRng-3.7.4.new/Makefile.in
---- LPRng-3.7.4/Makefile.in	Thu Dec 28 14:05:42 2000
-+++ LPRng-3.7.4.new/Makefile.in	Fri Apr 27 21:56:02 2001
+--- LPRng-3.7.5/Makefile.in.wiget	Mon Jan 15 22:27:47 2001
++++ LPRng-3.7.5/Makefile.in	Tue Oct  9 14:53:45 2001
 @@ -44,7 +44,6 @@
  LOCKFILE=\"@LOCKFILE@\"
  PSHOWALL="@PSHOWALL@"
@@ -383,8 +416,17 @@ diff -Nru LPRng-3.7.4/Makefile.in LPRng-3.7.4.new/Makefile.in
 -LOCALEDIR=@LOCALEDIR@
  INIT=@INIT@
  USE_NLS=@USE_NLS@
+ USE_GDBM=@USE_GDBM@
+@@ -58,7 +57,7 @@
+ # ALLDIRS for other such as documentation
+ #=============================================================================
  
-@@ -108,7 +107,7 @@
+-DIRS= UTILS ${USE_GDBM_BUILD_DIR} intl src po man
++DIRS= UTILS intl src po man
+ INSTALLDIRS= UTILS intl src po man
+ FILES=./postinstall ./preremove ./postremove ./lpd.conf
+ ALLDIRS= ${DIRS} ${SRC}/TESTSUPPORT ${SRC}/HOWTO ${SRC}/DISTRIBUTIONS
+@@ -113,7 +112,7 @@
  ###############################################################################
  $(ALLDIRS): FRC
  	if [ "$@" != po -o "$(USE_NLS)" != "no" ] ; then \
